### ISSUE TITLE
Configuration question

### ISSUE THREAD

**Issue by LSTANCZYK** [CoreyHayward/PowerToys-Run-InputTyper#3]
How do you configure this plugin with pre-defined text?

**Comment by CoreyHayward** [comment]
The is no configuration for pre-defined text, since you can have a range of different passwords for different accounts, I can't really see the use case for this. However, once you have typed the input once, it remains in the input box which you can then just re-use.

The idea is that the PowerToys Run input can accept pasted text therefore the workflow I use this with is to copy the password into the PTRun input with the "@@" prefix and then hit enter and it will type the input for you!

I do have plans to add functionality to copy direct from the clipboard if no input is entered following the "@@" which I will hopefully be able to work on soon!
