### ISSUE TITLE
Feature Enhancement: Snippet Manager - Text Expander

### ISSUE THREAD

**Issue by pa-0** [CoreyHayward/PowerToys-Run-InputTyper#6]
Still mulling over this concept and exactly how it could be implemented but first thought I had when I saw this project is that there is potential for it to be expanded as a means to quickly access predefined snippets/templates of text and inserting them anywhere system wide.

**Comment by maraf** [comment]
@pa-0 I had similar idea and put it into a prototype https://github.com/neptuo/Productivity.SnippetManager. 
It's not a powertoy plugin, on the other hand it positions the snippet window next to the cursor 😎

**Comment by CoreyHayward** [comment]
@pa-0 I really like this idea, however I think it is more similar to one of my other PTRun plugins ([ClipboardManager](https://github.com/CoreyHayward/PowerToys-Run-ClipboardManager)) however instead of listing the clipboard contents it would list snippets which could be created and managed via the PTRun UI (context menu options for adding and removing snippets).

I think I'd like to keep this separate from this plugin as it was designed specifically to emulate manual typing in situations where that is required and adding a whole snippet manager to this would deviate a bit from its purpose.

I'll take a stab at a standalone snippet manager plugin [here](https://github.com/CoreyHayward/PowerToys-Run-Snippets) would love for any feedback or suggestions for functionality you have!

**Comment by CoreyHayward** [comment]
@pa-0 Initial version is out, hopefully you find it useful! 
https://github.com/CoreyHayward/PowerToys-Run-Snippets

I'll close this as resolved, if you have any specific requests for features feel free create an issue on the repo!
